export const DONATORS_LIST_REQUEST = 'DONATORS_LIST_REQUEST';
export const DONATORS_LIST_SUCCESS = 'DONATORS_LIST_SUCCESS';
export const DONATORS_LIST_FAIL = 'DONATORS_LIST_FAIL';
export const DONATORS_LIST_RESET = 'DONATORS_LIST_RESET';

export const REQUESTERS_LIST_REQUEST = 'REQUESTERS_LIST_REQUEST';
export const REQUESTERS_LIST_SUCCESS = 'REQUESTERS_LIST_SUCCESS';
export const REQUESTERS_LIST_FAIL = 'REQUESTERS_LIST_FAIL';
export const REQUESTERS_LIST_RESET = 'REQUESTERS_LIST_RESET';

export const UNVERIFIED_LIST_REQUEST = 'UNVERIFIED_LIST_REQUEST';
export const UNVERIFIED_LIST_SUCCESS = 'UNVERIFIED_LIST_SUCCESS';
export const UNVERIFIED_LIST_FAIL = 'UNVERIFIED_LIST_FAIL';
export const UNVERIFIED_LIST_RESET = 'UNVERIFIED_LIST_RESET';

export const USER_VERIFY_REQUEST = 'USER_VERIFY_REQUEST';
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS';
export const USER_VERIFY_FAIL = 'USER_VERIFY_FAIL';
