export const DONATION_CREATE_REQUEST = 'DONATION_CREATE_REQUEST';
export const DONATION_CREATE_SUCCESS = 'DONATION_CREATE_SUCCESS';
export const DONATION_CREATE_FAIL = 'DONATION_CREATE_FAIL';

export const REQUESTERS__FOR_DONATORS_LIST_REQUEST =
  'REQUESTERS__FOR_DONATORS_LIST_REQUEST';
export const REQUESTERS__FOR_DONATORS_LIST_SUCCESS =
  'REQUESTERS__FOR_DONATORS_LIST_SUCCESS';
export const REQUESTERS__FOR_DONATORS_LIST_FAIL =
  'REQUESTERS__FOR_DONATORS_LIST_FAIL';
export const REQUESTERS__FOR_DONATORS_LIST_RESET =
  'REQUESTERS__FOR_DONATORS_LIST_RESET';
