export const REQUEST_CREATE_REQUEST = 'REQUEST_CREATE_REQUEST';
export const REQUEST_CREATE_SUCCESS = 'REQUEST_CREATE_SUCCESS';
export const REQUEST_CREATE_FAIL = 'REQUEST_CREATE_FAIL';

export const DONATORS_FOR_REQUESTER_LIST_REQUEST =
  'DONATORS_FOR_REQUESTER_LIST_REQUEST';
export const DONATORS_FOR_REQUESTER_LIST_SUCCESS =
  'DONATORS_FOR_REQUESTER_LIST_SUCCESS';
export const DONATORS_FOR_REQUESTER_LIST_FAIL =
  'DONATORS_FOR_REQUESTER_LIST_FAIL';
export const DONATORS_FOR_REQUESTER_LIST_RESET =
  'DONATORS_FOR_REQUESTER_LIST_RESET';
